### ISSUE TITLE
提问 这几个人是怎么样的P♂Y关系

### ISSUE THREAD

**Issue by SoraKasvgano** [kochiyasanae1/ProjectPoi#1]
@kagurazakasanae 
@Angelic47 
@kasuganosoras
@Archeb
这个问题困扰了我很多年

**Comment by kagurazakasanae** [comment]
not related with this project

**Comment by Angelic47** [comment]
Haven't met you, but it's rude to analyze someone else's relationship chain. Your question doesn't make any sense, all you listed there are ordinary netizens and have no other relationship. Stop your violation of other people's privacy.

**Comment by kasuganosoras** [comment]
请不要随意通过 @ 打扰其他人，大家都很忙，研究别人的关系链并且还直接询问是非常不礼貌的行为。没有什么特别的关系，只是认识或者在一个群里而已，请停止你窥探他人隐私的行为。
